nome = input('Digite o nome da Aluna:')
idade = int(input('Digite a idade da aluna:'))
altura = float(input('Digite a altura da aluna:'))
hobbies = input('Digite os hobbies da aluna separados por vírgula:')
hobbies1 = hobbies.split ('.')
endereco_rua = input('Digite o nome da rua da aluna:')
endereco_numero = input('Digite o numero da casa da aluna:')
endereco_cidade = input('Digite a cidade da aluna:')
endereco = (endereco_rua, endereco_numero, endereco_cidade)
email = input ('Digite o email da aluna:')
telefone = input ('Digite o telefone da aluna:')
contato ={'email': email, 'telefone': telefone}

print ('\nOlá, segue informações sobre aluna:')
print ('nome:', nome)
print ('idade', idade)
print ('altura', altura)
print ('hobbies', hobbies1)
print ('endereco', endereco)
print ('contato', contato)
